# Generated by Django 4.0.2 on 2022-02-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
