# Generated by Django 4.0.2 on 2022-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_category_options_alter_visualart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualart',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
