# Generated by Django 4.0.2 on 2022-02-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_by', models.CharField(max_length=32)),
                ('comment', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('visualart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.visualart')),
            ],
        ),
    ]
