# Generated by Django 4.0.2 on 2022-02-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_blogcategory_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.blogcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
