# Generated by Django 4.0.2 on 2022-03-27 12:00

from django.db import migrations, models

def set_initial_order(apps, schema_editor):
    model = apps.get_model('posts', 'VisualArt')
    for s in model.objects.all():
        s.order = s.pk
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_options_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.RunPython(
            set_initial_order,
            reverse_code=lambda apps, schema_editor: None
        ),
    ]
