# Generated by Django 4.0.2 on 2022-03-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_visualart_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visualart',
            options={'ordering': ['-order'], 'verbose_name': 'art', 'verbose_name_plural': 'arts'},
        ),
    ]
