# Generated by Django 4.0.2 on 2022-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualart',
            name='thumbnail',
            field=models.ImageField(default=None, null=True, upload_to='thumbnails/'),
        ),
    ]
