# Generated by Django 4.0.2 on 2024-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_visualart_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualart',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='thumbnails/'),
        ),
    ]
