# Generated by Django 4.0.2 on 2024-05-16 08:07


from io import BytesIO
import os

from PIL import Image
from django.db import migrations, models

from posts.utils import FirebaseImageUploader, ImageProcessor

firebase = FirebaseImageUploader()


def update_visualart_fields(apps, schema_editor):
    image_processor = ImageProcessor()

    VisualArt = apps.get_model("posts", "VisualArt")

    for artwork in VisualArt.objects.all():
        if artwork.art:
            if not os.path.exists(f"media/{artwork.art}"):
                continue

            artwork_uploaded_to_path = artwork.art
            artwork_filename = artwork_uploaded_to_path.replace("art/", "")

            image_file_contents = None
            with open(f"media/{artwork.art}", "rb") as f:
                image_file_contents = f.read()

            # Open the main artwork as a file and upload it
            artwork.art = firebase.upload_file(
                BytesIO(image_file_contents), file_name=artwork_filename
            )

            # Make the thumbnail and upload it
            artwork_PIL_Image = Image.open(f"media/{artwork_uploaded_to_path}")
            MAX_SIZE = (1200, 1200)
            artwork_PIL_Image.thumbnail(MAX_SIZE)
            thumbnail_buffer = BytesIO()

            ext = artwork_filename.split(".")[-1].lower()

            if ext in ["jpg", "jpeg"]:
                ftype = "JPEG"
            elif ext == "gif":
                ftype = "GIF"
            elif ext == "png":
                ftype = "PNG"
            else:
                ftype = "PNG"
            artwork_PIL_Image.save(thumbnail_buffer, format=ftype)
            thumbnail_buffer.seek(0)

            artwork.thumbnail = firebase.upload_image(
                image_processor.create_inmemory_uploaded_file(
                    thumbnail_buffer, filename=f"thumnail.{artwork_filename}"
                )
            )

        artwork.save()


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0017_alter_visualart_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visualart",
            name="art",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="visualart",
            name="thumbnail",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.RunPython(update_visualart_fields),
    ]
