# Generated by Django 4.0.2 on 2024-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_visualart_art_alter_visualart_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visualart',
            old_name='art',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='visualart',
            name='additional_images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
